<a href="https://colab.research.google.com/github/Gattuvamsi/Deep_Learning/blob/main/2203A52127_DL_A1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#withou using libraries
Y_actual = [20, 30, 40, 50, 60]
Y_pred = [20.5, 30.3, 40.2, 50.6, 60.7]


def calculate_error_metrics(y_actual, y_pred):
    n = len(y_actual)
    mae = sum(abs(y - y_hat) for y, y_hat in zip(y_actual, y_pred)) / n
    mse = sum((y - y_hat) ** 2 for y, y_hat in zip(y_actual, y_pred)) / n
    rmse = mse ** 0.5
    return mae, mse, rmse


mae, mse, rmse = calculate_error_metrics(Y_actual, Y_pred)


print(f"Mean Absolute Error (MAE): {mae}")
print(f"Mean Squared Error (MSE): {mse}")
print(f"Root Mean Squared Error (RMSE): {rmse}")


Mean Absolute Error (MAE): 0.4600000000000016
Mean Squared Error (MSE): 0.24600000000000147
Root Mean Squared Error (RMSE): 0.49598387070549127


In [14]:
#using libraries
import numpy as np
from sklearn.metrics import mean_squared_error,mean_absolute_error

y_act=[20,30,40,50,60]
y_pred=[20.5,30.3,40.2,50.6,60.7]

mse=mean_squared_error(y_act,y_pred)
rmse=np.sqrt(mse)
mae=mean_absolute_error(y_act,y_pred)

print(f"Mean Absolute Error (MAE): {mae}")
print(f"Mean Squared Error (MSE): {mse}")
print(f"Root Mean Squared Error (RMSE): {rmse}")

Mean Absolute Error (MAE): 0.4600000000000016
Mean Squared Error (MSE): 0.24600000000000147
Root Mean Squared Error (RMSE): 0.49598387070549127


In [13]:
#2
#calculate confusion matrix without predefined modules
y_act=[0,0,0,0,0,1,1,1,1,1,2,2,2,2,2]
y_pred=[0,0,1,2,2,1,0,2,0,2,0,0,1,2,2]

length=len(y_act)

confusion_matrix=[[0,0,0,],[0,0,0],[0,0,0]]

for i in range(length):
  if y_act[i]==0:
    if y_pred[i]==0:
      confusion_matrix[0][0]+=1
    elif y_pred[i]==1:
      confusion_matrix[0][1]+=1
    else:
      confusion_matrix[0][2]+=1
  elif y_act[i]==1:
    if y_pred[i]==0:
      confusion_matrix[1][0]+=1
    elif y_pred[i]==1:
      confusion_matrix[1][1]+=1
    else:
      confusion_matrix[1][2]+=1
  else:
    if y_pred[i]==0:
      confusion_matrix[2][0]+=1
    elif y_pred[i]==1:
      confusion_matrix[2][1]+=1
    else:
      confusion_matrix[2][2]+=1
print("confusion matrix:")
for row in confusion_matrix:
  print(row)

#Accuracy
accuracy=confusion_matrix[0][0]+confusion_matrix[1][1]+confusion_matrix[2][2]
accuracy=accuracy/length

print(f"Accuracy: {accuracy}")

confusion matrix:
[2, 1, 2]
[2, 1, 2]
[2, 1, 2]
Accuracy: 0.3333333333333333


In [18]:
y_act=[0,0,0,0,0,1,1,1,1,1,2,2,2,2,2]
y_pred=[0,0,1,2,2,1,0,2,0,2,0,0,1,2,2]

length=len(y_act)

from sklearn.metrics import confusion_matrix,accuracy_score
confusion_matrix=confusion_matrix(y_act,y_pred)
print("confusion matrix:")
print(confusion_matrix)

accuracy=accuracy_score(y_act,y_pred)
print(f"Accuracy: {accuracy}")

confusion matrix:
[[2 1 2]
 [2 1 2]
 [2 1 2]]
Accuracy: 0.3333333333333333
